### ISSUE TITLE
Plugin fails on Release

### ISSUE THREAD

**Issue by kira2015** [balvinderz/video_player_web_hls#11]
Plugin fails on Release, cannot play HLS 
`flutter build web --release`

**Comment by kira2015** [comment]
Because index.html is refactored
` <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"  type="application/javascript"></script>
`

**Comment by balvinderz** [comment]
it is not running on the latest version of hls.js?

**Comment by balvinderz** [comment]
![image](https://user-images.githubusercontent.com/30950893/123978432-79d60100-d9dd-11eb-92df-4feb00b79eb5.png)
works for me

**Comment by kira2015** [comment]
Sorry, my problem has been solved now
