### ISSUE TITLE
Chrome slow start

### ISSUE THREAD

**Issue by armen181** [balvinderz/video_player_web_hls#14]
I try Safari and Firefox and both perform well but Chrome is slow it takes around 8 second to start. you can see it on video.

https://www.youtube.com/watch?v=AAQK2J0WoZ4 

Is there any solution?

**Comment by balvinderz** [comment]
can you share the link that you are trying  to play.

**Comment by armen181** [comment]
Here is an example of a live video that starts late in the Chrome browser 
http://178.160.245.148:1935/edge3/smil:englishclub/playlist.m3u8
http://178.160.245.145:1935/edge2/smil:euronewsen/playlist.m3u8

**Comment by armen181** [comment]
I don't know what changed, seems that now it works as on other browsers, Thanks
