### ISSUE TITLE
Change video quality support

### ISSUE THREAD

**Issue by aramisromero89** [balvinderz/video_player_web_hls#15]
Is it possible to extend VideoPlayerController so I can change the video quality of hls streams. Hls.js supports changing the video quality but I can't figure out how to call the Hls.js api.

**Comment by balvinderz** [comment]
it is not possible to do this in this plugin , because i can only use methods that are supported in the official video_player plugin.
if they add support for changing video quality in video_player , i will add support for that in this plugin.

**Comment by aramisromero89** [comment]
> it is not possible to do this in this plugin , because i can only use methods that are supported in the official video_player plugin.
> if they add support for changing video quality in video_player , i will add support for that in this plugin.

Is there any workaround so I can change the quality. Is there any package or plugin that enables this feature?

**Comment by balvinderz** [comment]
there is better_player but it only supports android and ios.

**Comment by aramisromero89** [comment]
I solved my problem by reinitializing the VideoPlayerController object with the desired video quality url obtained from master.m3u8 file. Previously I saved the position and seek to it when new controller is ready.

**Comment by balvinderz** [comment]
nice

**Comment by balvinderz** [comment]
should i close this?

**Comment by aramisromero89** [comment]
If you think this is a good solution, please feel free.

**Comment by balvinderz** [comment]
i will open this again if they add support for changing video quality in video_player.
