### ISSUE TITLE
[video_player_web_hls] Refused to set unsafe header "Cookie"

### ISSUE THREAD

**Issue by mrinaljain** [balvinderz/video_player_web_hls#17]
I am using the video_player_web_hls on top of flick_video_player to play .m3u8 videos  in my flutter web app. the plugin works fine for normal .m3u8 URLs but when I am trying to implement signed cookies  for web and pass cookies in header. I get the following error which says  **Refused to set unsafe header "Cookie"**
![Screenshot 2021-09-10 at 1 55 26 PM](https://user-images.githubusercontent.com/7473761/132825936-a0c84887-cd96-4a53-b4d2-9238e2fee97d.png)

Can you please help me out if its something wrong implemented from my side or its problem from the plugin side.

Following is my  sudo code examples which I have tried 
            

1. Example 1

        `String cookie = "CloudFront-Policy=$cloudFrontPolicy" + ";CloudFront-Signature=$loudFrontSignature" +
              ";CloudFront-Key-Pair-Id=$cloudFrontKeyPairId";
  
          httpHeaders = {
            "useCookie": "true",
            "Cookie": cookie,
          };
          
          playerController = VideoPlayerController.network(playUrl,
            httpHeaders: httpHeaders,
         );`

2. Example 2

          `httpHeaders = {
             "useCookie": "true",
            "CloudFront-Policy": "${_cookieDetails.cloudFrontPolicy}",
            "CloudFront-Signature": "${_cookieDetails.cloudFrontSignature}",
            "CloudFront-Key-Pair-Id": "${_cookieDetails.cloudFrontKeyPairId}"
          };
          
          playerController = VideoPlayerController.network(playUrl,
            httpHeaders: httpHeaders,
         );`

**Comment by balvinderz** [comment]
It should be useCookies not useCookie

**Comment by mrinaljain** [comment]
Sorry I am using useCookies only but I wrote useCookie here by mistake.

The code is live here if you wanna have a look and debug
http://m.stage.in/

**Comment by balvinderz** [comment]
<img width="1429" alt="Screenshot 2021-09-12 at 3 39 26 PM" src="https://user-images.githubusercontent.com/30950893/132983600-3978f2e2-34e4-4810-bc81-fa882cf8a782.png">
all i get on your videos are CORS errors.

**Comment by mrinaljain** [comment]
Can we connect over a quick vc so that I can explain the problem much better.

Whatever time suits you the best.

**Comment by balvinderz** [comment]
On Saturday , after 11 am . You can message me on discord - balvinderz#1151

**Comment by balvinderz** [comment]
Closing because this is inactive for a long time.

**Comment by CawStack** [comment]
Hello @mrinaljain @balvinderz, I am getting the same error while trying to login to my web app, have you managed to resolve yours?
