### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by wilssola** [balvinderz/video_player_web_hls#2]
Hello, even with the plugin I keep getting this error what can I do to fix it?

Uncaught (in promise) Error: PlatformException (MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser).)

Thank you very much in advance!

**Comment by balvinderz** [comment]
did you add the script tag of hls.js ?

**Comment by balvinderz** [comment]
` <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"  type="application/javascript"></script>
`

**Comment by wilssola** [comment]
Yes, I added it

**Comment by balvinderz** [comment]
Can you send me link that you are trying to play

**Comment by wilssola** [comment]
Here: https://firebasestorage.googleapis.com/v0/b/flybis.appspot.com/o/0SvPtKGRuJPEY7OFqzBBlaPUSBh2%2Fposts%2Fvideos%2F7e35b8d6-d457-4b4e-b53e-87b5f1a44a8d%2Fmaster.m3u8?alt=media&token=47a9f631-f068-4e7b-b758-76266871092b

**Comment by balvinderz** [comment]
the current plugins plays m3u8 only if the link ends with .m3u8 . i will try to fix this .

**Comment by balvinderz** [comment]
try now . i updated the package. if you run this link on localhost , you will get cors error so disable that before trying.

**Comment by rickbox** [comment]
Thank you very much for making.
I updated 0.1.3.
I can play this link.
https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8
But I can't play this link.
https://storage.googleapis.com/gameclip-prod/videos/1202523991404998656/1202523991404998656.m3u8
Do you know why ?

**Comment by balvinderz** [comment]
> Thank you very much for making.
> I updated 0.1.3.
> I can play this link.
> https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8
> But I can't play this link.
> https://storage.googleapis.com/gameclip-prod/videos/1202523991404998656/1202523991404998656.m3u8
> Do you know why ?

Because of CORS .

**Comment by rickbox** [comment]
Thank you.
