### ISSUE TITLE
WEB - Azure URL links are different

### ISSUE THREAD

**Issue by milodude** [balvinderz/video_player_web_hls#20]
I have gone through the example link an everything went fine. I have created a stream in Azure services and  I have been given several options but none of them are suitable to the example in hand. I'm not an expert in video streaming but was wondering how this could be achieved.

`hls : https://gnmservicerecording-usea.streaming.media.azure.net/f1b83d9e-e09f-4bc8-a6bb-21b232ea058b/174939a2-0ac8-405f-b0ef-b34429c2bac3.ism/manifest(format=m3u8-aapl)`

`DASH: https://gnmservicerecording-usea.streaming.media.azure.net/f1b83d9e-e09f-4bc8-a6bb-21b232ea058b/174939a2-0ac8-405f-b0ef-b34429c2bac3.ism/manifest(format=mpd-time-csf)`

`smoothstreaming: https://gnmservicerecording-usea.streaming.media.azure.net/f1b83d9e-e09f-4bc8-a6bb-21b232ea058b/174939a2-0ac8-405f-b0ef-b34429c2bac3.ism/manifest`

None of them are working and I'm getting this error

![image](https://user-images.githubusercontent.com/4110660/139294868-8f5fed0a-8ee2-4445-babc-a3dd2dda0766.png)

I have also added the script tag before the head in the index.html.
If I use the smoothStreaming url in this link I can see that the format it is supported 
[https://ampdemo.azureedge.net/?url=https%3A%2F%2Fgnmservicerecording-usea.streaming.media.azure.net%2Ff1b83d9e-e09f-4bc8-a6bb-21b232ea058b%2F174939a2-0ac8-405f-b0ef-b34429c2bac3.ism%2Fmanifest](url)

Any advice or help will be much appreciated.

**Comment by balvinderz** [comment]
You can check if a link is playable by this plugin here: https://hls-js.netlify.app/demo/

I tried the hls link that you provided and the hls.js player got this error.
![image](https://user-images.githubusercontent.com/30950893/139568808-c561f0c5-b9d0-4486-9037-da32b1fb5926.png)

**Comment by balvinderz** [comment]
This type of video will require this https://ampdemo.azureedge.net/

i will try to integrate this  type of video player and create a branch for you to use.

**Comment by milodude** [comment]
> This type of video will require this https://ampdemo.azureedge.net/
> 
> i will try to integrate this type of video player and create a branch for you to use.

Hello, I have talked to my PM and he has agreed for me to search for a way  to fix this issue. They are willing to pay for your work in order to push these changes in. Would you be interested in make these changes? If so I would appreciate if you contact me and send me a budget estimation. Thanks in advanced.

**Comment by balvinderz** [comment]
I have sent you an email on the email that is given in your github id @milodude

**Comment by balvinderz** [comment]
Closing because this is inactive for a long time.
