### ISSUE TITLE
Only audio is being played on iOS safari & chrome

### ISSUE THREAD

**Issue by shreejeetp** [balvinderz/video_player_web_hls#28]
Im trying to play .hls video on a flutter web project. It is working on every other browser except for safari on iOS. Only audio is being played, while the video player displays nothing. Seems like this [issue](https://stackoverflow.com/questions/43287226/hls-video-streaming-on-ios-safari). Are there any workarounds to make it work?

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel unknown, 3.0.5, on Ubuntu 22.04 LTS 5.15.0-1020-aws, locale en_US.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> [☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
>     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
>     ✗ ProcessException: Failed to find "pkg-config" in the search path.
>         Command: pkg-config 
> [!] Android Studio (not installed)
> [✓] Connected device (1 available)
> [✓] HTTP Host Availability

Tried with video_player_web_hls 0.1.11+4

**Comment by balvinderz** [comment]
can you share the url you are trying to play.

**Comment by shreejeetp** [comment]
I wont be able to share the link of the video but is it possible to add a condition for ios web agents to not use this package. Because if i remove this package, the video starts working on ios but fails on chrome of other platforms.

**Comment by balvinderz** [comment]
Published 0.1.11+5 with the fix. Check if that works for you.

**Comment by balvinderz** [comment]
closing this as no update is given.
