### ISSUE TITLE
Can't play videos in iOS's Safari browser

### ISSUE THREAD

**Issue by HG9558** [balvinderz/video_player_web_hls#30]
I now use the latest version of the plug -in, but I can’t make video playback on iOS’s Safari, only the sound

**Comment by balvinderz** [comment]
Does it work on 0.1.11+4 ?

**Comment by HG9558** [comment]
I use [0.1.11+5] version
There is only sound now, no picture

<img width="449" alt="image" src="https://user-images.githubusercontent.com/22909991/198952216-f447c488-8a16-455c-a248-14d7798acdb7.png">

This is the response information of the video source

**Comment by balvinderz** [comment]
Can you try once with 0.1.11+4

**Comment by HG9558** [comment]
I have tried this, but the same, only sound, no picture

This is the version I relied on
  video_player: ^2.4.5
  video_player_web_hls: 0.1.11+4


I tried to use a lot of other plug -ins, which could not be achieved. Only your plug -in is almost close to my needs.
thanks

**Comment by balvinderz** [comment]
Can you share the url you are trying to play if possible

**Comment by HG9558** [comment]
https://websportplay.hngable.com/live/sd-1-3759738.m3u8
This is normal to play on Android and iOS platforms, but in the web application, the Safari browser has only sound, no picture

**Comment by HG9558** [comment]
Are you here, I am very anxious, 🙏

**Comment by balvinderz** [comment]
Link has stopped working. Can you share a new one

**Comment by HG9558** [comment]
okay，https://websportplay.hngable.com/live/sd-1-3836361/m3u8

Please try this link

From now on, I have kept online. If the link is invalid, please inform me in time. I will provide you with a new link to you

**Comment by balvinderz** [comment]
After using this link I am getting CORS error

**Comment by HG9558** [comment]
But there is no restriction on CORS in this side

**Comment by HG9558** [comment]
And when running with your Example, it can be played normally in the simulator of the Chrome browser. Only the Safari browser cannot be played

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/22909991/199012973-dce53465-2385-4b43-a5c7-07382ffc8a21.png">

**Comment by HG9558** [comment]
If the link fails, you can use this to try
https://websportplay.hngable.com/live/sd-1-3836676.m3u8
Please help, thank you

**Comment by balvinderz** [comment]
Published 0.1.11+6. Try  running your app with this version

**Comment by HG9558** [comment]
okay

**Comment by HG9558** [comment]
Thank you, the problem has been solved。 👍

**Comment by balvinderz** [comment]
welcome. closing the issue
