### ISSUE TITLE
Headers not working

### ISSUE THREAD

**Issue by rashid-abdulla** [balvinderz/video_player_web_hls#31]
I'm trying to pass the headers when playing m3u8 videos. Unfortunately, it isn't working somehow. Please refer to the screenshots.

My Code being

```
 _videoPlayerController =
              VideoPlayerController.network(videoUrl, httpHeaders: {
        'Cookie': "Cookies dummy string",
        'useCookie': "true",
        'useCookies': "true",
      })
```

<img width="755" alt="Screenshot 2022-10-31 at 5 31 46 PM" src="https://user-images.githubusercontent.com/28691569/199003853-c28570e7-d222-4afa-a450-58e8198e0dd3.png">

**Comment by balvinderz** [comment]
try document.cookie = "some value" before initializing the video

**Comment by balvinderz** [comment]
i think cookie is not send when using localhost ( I can be wrong)
