### ISSUE TITLE
Update to work with latest version of hls.js

### ISSUE THREAD

**Issue by sandeshgyw** [balvinderz/video_player_web_hls#38]
```
PlatformException(MEDIA_ERR_NETWORK, mediaError, fragParsingError, null)
```

I started getting this error all of a sudden from yesterday. Not quite sure but I think it's related to the latest upgrade of hls.js as the same videos were getting played prior to that.

**Comment by balvinderz** [comment]
Can you share a url that you are trying to play and on which browser.
