### ISSUE TITLE
[Bug] Video does not play on iOS Safari

### ISSUE THREAD

**Issue by wreppun** [balvinderz/video_player_web_hls#5]
To reproduce:
- Build and deploy the example
- Open up an iPhone simulator
- Open safari and navigate to the example
- Hit play

Current behavior:
- Nothing happens

Expected behavior:
- The video plays

I'll have a PR ready for this shortly.

**Comment by balvinderz** [comment]
Merged #6

**Comment by balvinderz** [comment]
Also published on pub.dev
