### ISSUE TITLE
Upgrade dependency to web 1.0.0 

### ISSUE THREAD

**Issue by blaneyneil** [balvinderz/video_player_web_hls#63]
By pinning the web dependency to 0.5.1 it's breaking a lot of other packages.  When I override to web ^1.0.0 the following errors are thrown:

video_player.dart:418:54: Error: A value of type 'JSBoolean' can't be assigned to a variable of type 'bool'.
        _videoElement.disablePictureInPicture = true.toJS;
                                                     ^
video_player.dart:428:50: Error: A value of type 'JSBoolean' can't be assigned to a variable of type 'bool'.
      _videoElement.disableRemotePlayback = true.toJS;
                                                 ^

**Comment by balvinderz** [comment]
Fixed in 1.3.0. Thanks for reporting. Closing the issue
